# WEEK01: Palmer Penguins Dataset

| Key              | Value                                                                                                                                                                                                                                                                                                            |
|:-----------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Week01** | Palmer Penguins Dataset                                                                                                                                                                                                                                                                                            |
| **Course Names** | Machine Learning and Data Science.                                                                                                                                                                                               |
| **Submission Deadline**     | September 23, 2026, 10:00 PM                                                                                                                                                                                                                                                                                          |
| **Student Name**     | Edward Chisaka                                                                                                                                                                                                                                                                                                     |
| **Contact**      | edward.chisaka@stud.hslu.ch                                                                                                                                                                                                                                                                                           |
| **Note**         | The link directs to the specific GitHub file for this _Week01_ Lab implementation exercise.<br/> **_Palmer Penguins_** dataset using Python.<br/> _The goal is to get familiar with data exploration: making plots, computing statistics from the data, getting information about size of the data_. <br/> Github citation: [BibTeX](https://github.com/CH-CHISAKA/Machine_Learning_and_Data_Science/tree/main/04-assignments/assignment-01) |

# 01: Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

# 02: Loading and Display the Palmer Penguins Dataset

In [ ]:
# Loading the palmer penguins dataset
penguins = sns.load_dataset("penguins")

# Displaying the head(5) - first five row, and tail(5) last five rows of the dataset
print("Head of the dataset:")
display(penguins.head(5))

print("\nTail of the dataset:")
display(penguins.tail(5))

Head of the dataset:

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

Tail of the dataset:

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [12]:
# The size of the dataset
print(f"\nRows and Columns: {penguins.shape}")

# Column information and data types
print("\nColumn information and data types:")
display(penguins.info())

Rows and Columns: (344, 7)

Column information and data types:
<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

None

In [13]:
# Checking for missing values in the dataset
print("\nMissing values in the dataset:")
display(penguins.isnull().sum())

Missing values in the dataset:

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [14]:
# Statistical summary
print("\nStatistical summary of the dataset:")
display(penguins.describe(include='all'))

Statistical summary of the dataset:

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
count,344,344,342.000000,342.000000,342.000000,342.000000,333
unique,3,3,NaN,NaN,NaN,NaN,2
top,Adelie,Biscoe,NaN,NaN,NaN,NaN,Male
freq,152,168,NaN,NaN,NaN,NaN,168
mean,NaN,NaN,43.921930,17.151170,200.915205,4201.754386,NaN
std,NaN,NaN,5.459584,1.974793,14.061714,801.954536,NaN
min,NaN,NaN,32.100000,13.100000,172.000000,2700.000000,NaN
25%,NaN,NaN,39.225000,15.600000,190.000000,3550.000000,NaN
50%,NaN,NaN,44.450000,17.300000,197.000000,4050.000000,NaN
75%,NaN,NaN,48.500000,18.700000,213.000000,4750.000000,NaN
max,NaN,NaN,59.600000,21.500000,231.000000,6300.000000,NaN